### ISSUE TITLE
Add access to $nodes through controller

### ISSUE THREAD

**Issue by pcolaianni** [biosustain/plotify#7]
At the moment you can select a node only by clicking on it.

**Comment by pcolaianni** [comment]
@maciejkorzepa What do you think about adding a property into data[] elements like:
```javascript
{
  name: 'Node A',
  parent: null,
  selected: true
}
```
This way the parent controller can modify the _selected_ property and ancestry would update the plot as usual.

**Comment by maciejkorzepa** [comment]
@pasqoo This would make sense, but we should also consider how this change should be detected. I see two ways of doing that. 
1) Deep configuration object comparison in $doCheck() in the component - run on each turn of the digest cycle.
2) Changing reference to configuration object. 
```javascript
let copy = angular.copy(lineageData);
copy.data.find(d => d.name == 'someName').selected = true;
lineageData = copy;
```
or even without making a deep copy:
```javascript
lineageData.data.find(d => d.name == 'someName').selected = true;
lineageData = {data: lineageData.data, layout: lineageData.layout}
```

I think I would go with the second option, as the first adds unnecessary load.

**Comment by maciejkorzepa** [comment]
@pasqoo What should happen when some nodes have been manually selected in the plot and then the configuration object is updated with some nodes having `selected` property set to `true`?
1) Only `selected` property counts - if a node had been selected, but in a new config the `selected` property is not set or set to false, the node will be deselected.
2) Only nodes with `selected` set to `false` or `true` will be updated. Nodes with undefined `selected` property would preserve their previous selection.

I like option 1 more as it seems more consistent.

**Comment by pcolaianni** [comment]
I too think Option 1 is a good choice, because the parent can control that behavior through the `selected-nodes` binding. If it wants to keep the clicked nodes as selected, it could check which nodes are passed through $nodes and set their `selected` property accordingly when creating the new object.

**Comment by maciejkorzepa** [comment]
Option 1 of initializing set of selected nodes implemented. If we choose option 2 of how changes are detected (through reference), this issue can be closed.

**Comment by pcolaianni** [comment]
Since implementing the mentioned choice doesn't need any other modification, I would try this way and, in case of problems, we will open the issue again. Thanks :)
